#!/bin/bash

# AgroMind System - Simple Startup Checklist
# Print this file or follow along as you start the system

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     🌱 AgroMind AI Doctor - Startup Checklist             ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "Follow these steps to run AgroMind:"
echo ""
echo "✓ STEP 1: Navigate to Project Directory"
echo "  Command:"
echo "    cd \"/Users/jaid/Documents/Hackethone/DYP Kolhapur/agromind-final\""
echo ""
echo "✓ STEP 2: Start All Services"
echo "  Command:"
echo "    ./run.sh start"
echo "  Expected Output:"
echo "    - All 5 containers should show UP"
echo "    - Backend should show (healthy)"
echo "    - Database should show (healthy)"
echo "  Time: ~30 seconds to start"
echo ""
echo "✓ STEP 3: Verify Services Are Running"
echo "  Command:"
echo "    ./run.sh verify"
echo "  Look for:"
echo "    ✅ Container agromind-backend - UP"
echo "    ✅ Container agromind-frontend - UP"
echo "    ✅ Container agromind-db - UP"
echo "    ✅ Container agromind-ml - UP"
echo "    ✅ Container agromind-nginx - UP"
echo "    ✅ Backend API (port 3001) - RUNNING"
echo "    ✅ Frontend (port 3000) - RUNNING"
echo "    ✅ ML Service (port 5001) - RUNNING"
echo "    ✅ PostgreSQL - CONNECTED"
echo "    ✅ Chat History Table - EXISTS"
echo ""
echo "✓ STEP 4: Open in Web Browser"
echo "  URL:"
echo "    http://localhost:3000"
echo "  You should see:"
echo "    - AgroMind login page"
echo "    - Option to sign up or login"
echo ""
echo "✓ STEP 5: Test Chat Feature"
echo "  1. Login or create account"
echo "  2. Navigate to 'AI Doctor' section"
echo "  3. Select language (English, Hindi, or Marathi)"
echo "  4. Type a farming question"
echo "  5. See context-aware response"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                    🎉 YOU'RE DONE!                        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "Quick Troubleshooting:"
echo ""
echo "❌ Services won't start?"
echo "  → Run: ./run.sh clean"
echo "  → Then: ./run.sh start"
echo ""
echo "❌ Can't access http://localhost:3000?"
echo "  → Check: ./run.sh status"
echo "  → Frontend should show UP"
echo "  → Try: ./run.sh restart"
echo ""
echo "❌ Backend errors?"
echo "  → Watch logs: ./run.sh backend"
echo "  → Check health: curl http://localhost:3001/health"
echo ""
echo "❌ Database issues?"
echo "  → Connect: ./run.sh db-shell"
echo "  → Test: SELECT * FROM users LIMIT 1;"
echo ""
echo "Other Commands:"
echo "  ./run.sh stop              - Stop all services"
echo "  ./run.sh logs              - View all logs"
echo "  ./run.sh rebuild           - Rebuild after code changes"
echo "  ./run.sh help              - Show all commands"
echo ""
echo "Contact: Check logs with ./run.sh logs for error details"
echo ""
